// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABc7OpXb5lPztBNw15HmetBAQ_asfygOU',
    appId: '1:236068512629:android:f8a6ee6b1e6303ebdee93c',
    messagingSenderId: '236068512629',
    projectId: 'sfac-test-3309e',
    storageBucket: 'sfac-test-3309e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_SEq3PpPMOJy4fahZda731XTp6H5ri8',
    appId: '1:236068512629:ios:8469cf6fbcd983f5dee93c',
    messagingSenderId: '236068512629',
    projectId: 'sfac-test-3309e',
    storageBucket: 'sfac-test-3309e.appspot.com',
    androidClientId:
        '236068512629-igmfaedmosj2j8uuqct6o9dre91ts34n.apps.googleusercontent.com',
    iosClientId:
        '236068512629-u2dq2i650pf57hsq40qh2n8mu0s66pat.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
